# Generated by Django 6.1 on 2026-09-02 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_traitement', models.CharField(choices=[('suppression_fond', "Suppression d'arrière-plan"), ('effacement_objet', 'Effacement d’objet'), ('amelioration', 'Amélioration de la qualité'), ('upscaling', 'Agrandissement'), ('restauration', 'Restauration de photo'), ('generation', "Génération d'image"), ('transformation', 'Transformation artistique')], max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Disponible'), ('echec', 'Échec')], default='en_attente', max_length=15)),
                ('message_erreur', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='images_app.image')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
