# Generated by Django 6.1.1 on 2026-09-08 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_app.image'),
        ),
    ]
